services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: nexacarro-backend
    restart: unless-stopped

    ports:
      - "4000:4000"

    env_file:
      - ./backend/.env